name: 🧪 Run Unit Tests

on: [push, pull_request]

env:
  IMPORT_TIME: 10s

jobs:
  Tests:
    name: Run All Tests on 3.5
    runs-on: ubuntu-latest
    container: barichello/godot-ci:mono-3.5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          nuget restore
          mkdir -p .mono/assemblies/Debug
          cp /usr/local/bin/GodotSharp/Api/Release/* .mono/assemblies/Debug

      - name: Compile
        run: msbuild

      - name: Reimport Assets
        run: timeout $IMPORT_TIME godot --editor

      - name: Run
        run: godot addons/WAT/cli.tscn run=all 

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: test/results.xml
